  #  Configurações de intervalos de tempo
  time_intervals:
    # Intervalo de tempo para verificar se há heróis disponíveis para trabalhar
    # Valor padrão (em minutos): 10
    send_heroes_for_work: 10
    
    # Intervalo de tempo para atualizar a posição dos heróis no mapa
    # Valor padrão (em minutos): 3
    refresh_heroes_positions: 3
    
    # Intervalo de tempo para verificar por novos mapas
    # Valor padrão (em segundos): 5
    check_for_new_map_button: 5
    
    # Intervalo de tempo para verificar se precisa resolver o captcha.
    # Valor padrão (em minutos): 1
    check_for_captcha: 1

    # Intervalo de tempo para verificar se existe solicitação de login
    # Valor padrão (em minutos): 5
    check_for_login: 5

    # Intervalo de tempo entre movimentos
    # Valor padrão (em segundos): 1
    interval_between_moviments: 1


  # O quão confiante o bot precisa estar para clicar nos botões (valores entre 0 e 1. 0 é o valor mínimo, 1 é o valor máximo)
  threshold:
    # Valor padrão: 0.7
    default: 0.7

    # Valor padrão: 0.8
    commom: 0.8

    # Valor padrão: 0.8
    select_wallet_buttons: 0.8

    # Valor padrão: 0.9
    go_to_work_btn: 0.9

    # Valor padrão: 0.9
    green_bar: 0.9

  # Valor padrão: 60
  scroll_size: 60

  # Valor padrão: 3
  scroll_attemps: 3

  # Valor padrão: true
  use_click_and_drag_instead_of_scroll: true

  # Valor padrão: 200
  click_and_drag_amount: 200

  # Valor padrão: green
  # Opções disponíveis:
  # all   = seleciona todos os heróis (independente da barra de stamina)
  # green = seleciona os heróis com a barra de stamina verde (metade ou cheia)
  # full  = seleciona somente os heróis com a barra de stamina cheia
  select_heroes_mode: "green"

  # Opção para salvar os logs em arquivo (logs.txt)
  # Valor padrão : False
  # Opções disponíveis: False ou True
  save_log_to_file: True
